<?php
// tool_backup.php - Updated to use session password (download handling moved to main file)

// Handle backup preview
if (isset($_GET['view'])) {
    $file = $_GET['view'];
    if (file_exists($file)) {
        $content = file_get_contents($file);
        $line_count = count(file($file));
        $file_size = round(filesize($file) / 1024, 2);
        
        echo '<div class="fade-in">';
        echo '<div style="background: var(--info); color: white; padding: 15px; border-radius: 8px 8px 0 0; margin-bottom: 0;">';
        echo '<h4 style="margin: 0;">👀 Backup Preview: ' . basename($file) . '</h4>';
        echo '<p style="margin: 5px 0 0 0;">Lines: ' . $line_count . ' | Size: ' . $file_size . ' KB</p>';
        echo '</div>';
        echo '<div class="code" style="border-radius: 0 0 8px 8px; margin-top: 0;">';
        echo '<pre style="max-height: 500px; overflow: auto; margin: 0;">' . htmlspecialchars($content) . '</pre>';
        echo '</div>';
        echo '<div style="text-align: center; margin: 20px 0;">';
        echo '<a href="?tool=backup&download=' . urlencode($file) . '" class="button" style="background: var(--success); padding: 10px 20px; border-radius: 6px; text-decoration: none; color: white; margin-right: 10px;">📄 Download This Backup</a>';
        echo '<a href="?tool=backup" class="button" style="background: var(--gray); padding: 10px 20px; border-radius: 6px; text-decoration: none; color: white;">← Back to Backup Tool</a>';
        echo '</div>';
        echo '</div>';
        return; // Exit early to show only preview
    }
}

// Handle backup creation
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'backup') {
    // Get the root password from session
    $root_password = $_SESSION['mysql_root_password'] ?? '';
    
    if (empty($root_password)) {
        echo '<div class="error fade-in">Please login first to create backups.</div>';
    } else {
        $db_name = $_POST['db_name'];
        
        if (!empty($db_name)) {
            try {
                $backup_dir = '/tmp/backups/';
                if (!is_dir($backup_dir)) {
                    mkdir($backup_dir, 0755, true);
                }
                
                $timestamp = date('Y-m-d_H-i-s');
                $backup_file = $backup_dir . $db_name . '_' . $timestamp . '.sql';
                $zip_file = $backup_dir . $db_name . '_' . $timestamp . '.zip';
                
                // Backup database with proper formatting and line breaks
                $command = "mysqldump -u root -p'$root_password' --skip-comments --complete-insert --skip-dump-date $db_name 2>/dev/null";
                $output = shell_exec($command);
                
                if ($output) {
                    // Add proper header and formatting
                    $header = "-- MySQL Backup Generated by DBA Toolkit\n";
                    $header .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
                    $header .= "-- Database: $db_name\n";
                    $header .= "-- ------------------------------------------------------\n\n";
                    
                    $content = $header . $output;
                    
                    // Format INSERT statements with line breaks
                    $content = preg_replace_callback(
                        '/INSERT INTO `([^`]+)` VALUES (\([^)]+\))(,*)/',
                        function($matches) {
                            $values = $matches[2];
                            // Add line breaks after each row
                            $formatted_values = preg_replace('/\),\(/', "),\n(", $values);
                            return "INSERT INTO `" . $matches[1] . "` VALUES " . $formatted_values . $matches[3];
                        },
                        $content
                    );
                    
                    file_put_contents($backup_file, $content);
                    
                    // Create ZIP file
                    $zip = new ZipArchive();
                    if ($zip->open($zip_file, ZipArchive::CREATE) === TRUE) {
                        $zip->addFile($backup_file, basename($backup_file));
                        $zip->close();
                    }
                    
                    $file_size = round(filesize($backup_file) / 1024, 2);
                    $zip_size = round(filesize($zip_file) / 1024, 2);
                    $line_count = count(file($backup_file));
                    
                    echo '<div class="success fade-in">';
                    echo '<h3>✅ Backup Completed Successfully!</h3>';
                    echo "Database: <strong>$db_name</strong><br>";
                    echo "Backup file: <strong>" . basename($backup_file) . "</strong><br>";
                    echo "File size: <strong>$file_size KB</strong> (SQL), <strong>$zip_size KB</strong> (ZIP)<br>";
                    echo "Lines: <strong>$line_count</strong><br>";
                    echo '<div style="margin-top: 15px;">';
                    echo '<a href="?tool=backup&download=' . urlencode($zip_file) . '" class="button" style="background: var(--success); padding: 10px 20px; border-radius: 6px; text-decoration: none; color: white; margin-right: 10px;">📦 Download ZIP Backup</a>';
                    echo '<a href="?tool=backup&download=' . urlencode($backup_file) . '" class="button" style="background: var(--info); padding: 10px 20px; border-radius: 6px; text-decoration: none; color: white; margin-right: 10px;">📄 Download SQL Backup</a>';
                    echo '<a href="?tool=backup&view=' . urlencode($backup_file) . '" class="button" style="background: var(--warning); padding: 10px 20px; border-radius: 6px; text-decoration: none; color: var(--dark);">👀 Preview Backup</a>';
                    echo '</div>';
                    echo '</div>';
                } else {
                    throw new Exception('Backup failed. Check database name.');
                }
                
            } catch (Exception $e) {
                echo '<div class="error fade-in">';
                echo '<h3>⚠ Error</h3>';
                echo $e->getMessage();
                echo '</div>';
            }
        }
    }
}

// List existing backups
$backup_dir = '/tmp/backups/';
$backups = [];
if (is_dir($backup_dir)) {
    $files = scandir($backup_dir);
    foreach ($files as $file) {
        if ($file !== '.' && $file !== '..' && (pathinfo($file, PATHINFO_EXTENSION) === 'sql' || pathinfo($file, PATHINFO_EXTENSION) === 'zip')) {
            $backups[] = $file;
        }
    }
    rsort($backups); // Sort newest first
}
?>

<div class="columns-container">
    <div class="form-column">
        <!-- Backup Form -->
        <form method="post" action="?tool=backup" style="margin-bottom: 30px; padding: 20px; background: #f8f9fa; border-radius: 8px;">
            <h3>📤 Backup Database</h3>
            <input type="hidden" name="action" value="backup">
            
            <div class="form-group">
                <label for="backup_db_name">Database Name:</label>
                <input type="text" name="db_name" required placeholder="e.g., myapp_db">
            </div>
            
            <button type="submit">💾 Create Backup</button>
        </form>
        
        <div class="info">
            <h4>ℹ️ Note:</h4>
            <p>Using MySQL root password from your current session. No need to enter it again.</p>
        </div>
    </div>
    
    <div class="output-column">
        <?php if (!empty($backups)): ?>
        <h3>📦 Existing Backups</h3>
        <div style="max-height: 400px; overflow-y: auto;">
            <table style="width: 100%; border-collapse: collapse;">
                <thead>
                    <tr style="background: var(--primary); color: white;">
                        <th style="padding: 10px; text-align: left;">File Name</th>
                        <th style="padding: 10px; text-align: center;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($backups as $index => $backup): ?>
                    <tr style="background: <?php echo $index % 2 === 0 ? '#f8f9fa' : 'white'; ?>;">
                        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><?php echo htmlspecialchars($backup); ?></td>
                        <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: center;">
                            <?php
                            $file_path = $backup_dir . $backup;
                            $extension = pathinfo($backup, PATHINFO_EXTENSION);
                            ?>
                            <a href="?tool=backup&download=<?php echo urlencode($file_path); ?>" style="background: var(--success); color: white; padding: 5px 10px; border-radius: 4px; text-decoration: none; margin-right: 5px;" title="Download">📥</a>
                            <?php if ($extension === 'sql'): ?>
                            <a href="?tool=backup&view=<?php echo urlencode($file_path); ?>" style="background: var(--warning); color: var(--dark); padding: 5px 10px; border-radius: 4px; text-decoration: none;" title="Preview">👀</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php else: ?>
        <div class="output-placeholder">
            <h3>📁 No Backups Yet</h3>
            <p>Create your first backup using the form on the left</p>
        </div>
        <?php endif; ?>
    </div>
</div>

